### Etapa 1 - Tratamento dos Dados
- Carregar dataset e realizar inspeção inicial
- Verificar tipos de dados
- Identificar valores nulos e duplicados
- Analisar estatísticas descritivas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/dataset_analise_vendas.csv")
df

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Valor_Total,Cliente,Estado
0,1,2025-07-19,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Gabriel,MG
1,2,2025-08-18,Notebook,Eletrônicos,5.0,3500.0,17500.0,NaN,PB
2,3,2025-08-13,Livro Banco de Dados,Livros,1.0,120.0,120.0,Carlos,RJ
3,4,2025-04-28,NaN,Eletrônicos,1.0,350.0,350.0,Gabriel,NaN
4,5,2025-01-19,Mesa Escritório,Móveis,4.0,800.0,3200.0,Bruno,BA
...,...,...,...,...,...,...,...,...,...
495,496,2025-06-01,Smartphone,Eletrônicos,1.0,2200.0,2200.0,Fernanda,PE
496,497,2025-04-08,Curso Online,Educação,4.0,500.0,2000.0,Ana,BA
497,498,2025-01-13,Mesa Escritório,Móveis,2.0,800.0,1600.0,Fernanda,PE
498,499,2025-12-16,Notebook,Eletrônicos,5.0,NaN,17500.0,Fernanda,PR
499,500,2025-01-14,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Helena,RJ

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        500 non-null    int64
 1   Data            500 non-null    str
 2   Produto         477 non-null    str
 3   Categoria       474 non-null    str
 4   Quantidade      478 non-null    float64
 5   Preco_Unitario  479 non-null    float64
 6   Valor_Total     472 non-null    float64
 7   Cliente         470 non-null    str
 8   Estado          478 non-null    str
dtypes: float64(3), int64(1), str(5)
memory usage: 54.4 KB

In [4]:
df.describe()

         ID_Venda  Quantidade  Preco_Unitario   Valor_Total
count  500.000000  478.000000      479.000000    472.000000
mean   250.500000    2.960251      947.494781   2982.012712
std    144.481833    1.439372     1103.013553   4022.494443
min      1.000000    1.000000       90.000000     90.000000
25%    125.750000    2.000000      180.000000    480.000000
50%    250.500000    3.000000      500.000000   1200.000000
75%    375.250000    4.000000     1200.000000   3600.000000
max    500.000000    5.000000     3500.000000  17500.000000